sudo: required

language: python

#os:
#  - linux
#  - osx

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -y

# command to install dependencies
install:
  - sudo apt-get install pandoc
  - python -m pip install --upgrade pip
  - pip --version
  - pip install -r travis_requirements.txt

# command to run tests
script:
  - tox