language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install travis_requirements.txt
# command to run tests
script: tox